config/routes.rb
Rails.application.routes.draw do
  root "projects#index"

  resources :projects do
    resources :boards,  only: [:index, :new, :create]
  end

  resources :boards, only: [:show, :edit, :update, :destroy] do
    resources :tasks, only: [:index, :new, :create]
  end

  resources :tasks, only: [:show, :edit, :update, :destroy]

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/board.rb
class Board < ApplicationRecord
  belongs_to :project
  has_many :tasks
end

app/models/project.rb
class Project < ApplicationRecord
    has_many :boards

    validates :title, presence: true
    validates :description, presence: true, length: { minimum: 10 }
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :board
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/boards_controller.rb
class BoardsController < ApplicationController
  def index
    @project = Project.find(params[:project_id])
    @boards = Board.where('project_id':@project.id)
  end

  def show
    @board = Board.find(params[:id])
    @tasks = @board.tasks
    @project = @board.project
  end

  def create
    @project = Project.find(params[:project_id])
    @board = @project.boards.create(board_params)
    redirect_to project_path(@project)
  end

  def edit
    @board = Board.find(params[:id])
    @project = @board.project
  end

  def update
    @board = Board.find(params[:id])

    if @board.update(board_params)
      redirect_to @board
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @board = Board.find(params[:id])
    @project = @board.project
    @board.destroy

    redirect_to @project, status: :see_other
  end
  private
    def board_params
      params.require(:board).permit(:title, :description)
    end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def index
    @projects = Project.all
  end

  def show
    @project = Project.find(params[:id])
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(project_params)

    if @project.save
      redirect_to @project
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @project = Project.find(params[:id])
  end

  def update
    @project = Project.find(params[:id])

    if @project.update(project_params)
      redirect_to @project
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @project = Project.find(params[:id])
    @project.destroy

    redirect_to root_path, status: :see_other
  end

  private
  def project_params
    params.require(:project).permit(:title, :description)
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def show
    @task = Task.find(params[:id])
    @board = @task.board
    @project = @board.project
    @projectPath = "/projects/" + @project.id.to_s
    @boardPath = @projectPath+"/boards/" + @board.id.to_s
  end

  def edit
    @task = Task.find(params[:id])
  end
  
  def update
    @task = Task.find(params[:id])
    if(@task.update(task_params))
      redirect_to @task
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def new
    @task = Task.new
  end
  
  def create
    # See guide below for details on debugging (found it in Gemfile)
    # https://guides.rubyonrails.org/debugging_rails_applications.html#inspecting-variables
    # debugger
    @board = Board.find(params[:board_id])
    @task = @board.tasks.create(task_params)
    if(@task.save)
      redirect_to @task
    else
      render :edit, status: :unprocessable_entity
    end
  end

  private
    def task_params
      params.require(:task).permit(:title, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/boards_helper.rb
module BoardsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/boards/_board.html.erb
<p>
  <strong>Board :</strong>
  <%= link_to board.title, board %>
</p>

<p>
  <strong>About the Board:</strong>
  <%= board.description %>
</p>

app/views/boards/_form.html.erb
<%= form_with model: [ @project, @project.boards.build ] do |form| %>
  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </p>
  <p>
    <%= form.label :description %><br>
    <%= form.text_area :description %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/boards/_form1.html.erb
<%= form_with model: board do |form| %>
  <div>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </div>
  <div>
    <%= form.label :description %><br>
    <%= form.text_area :description %>
  </div>
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/boards/edit.html.erb
<h1>Edit Board</h1>


<%= form_with model: @board do |form| %>
 <div>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </div>
  <div>
    <%= form.label :description %><br>
    <%= form.text_area :description %>
  </div>
  <div>
    <%= form.submit %>
  </div>
  <% end %>

app/views/boards/index.html.erb
<h1>Boards for <%= @project.title %></h1>

<ol>
    <% @boards.each do |board| %>
    <li>
        <%= link_to board.title, project_path(@project) %>
    </li>
    <% end %>
</ol>

app/views/boards/show.html.erb
<h1><%= @board.title %></h1>

<%= @board.description %>

<ul>
  <li><%= link_to "Edit", edit_board_path(@board) %></li>
    <li><%= link_to "Destroy", board_path(@board), data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  } %></li>
  <li><%= link_to "Projects Index", root_path %></li>
</ul>
<p>
<strong>Project</strong> : <%= link_to @board.project.title, @board.project %>
</p>
<hr />

<h2>Tasks</h2>
<% if @board.tasks != [] %>
<%= render @board.tasks %>
<% else %>
    None
<% end %>
<hr />
<!--
  To enable debugging in the view section
  <%# console %>
-->

<h2>Add Task</h2>
<%= render 'tasks/form' %>
<hr />

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ProjectManagement</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/projects/_form.html.erb
<%= form_with model: project do |form| %>
  <div>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
    <% project.errors.full_messages_for(:title).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :description %><br>
    <%= form.text_area :description %><br>
    <% project.errors.full_messages_for(:description).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<h1>Edit Project</h1>

<%= render "form", project: @project %>

app/views/projects/index.html.erb
<h1>Projects</h1>

<ul>
  <% @projects.each do |project| %>
    <li>
      <%= link_to project.title, project %>
    </li>
  <% end %>
</ul>

<%= link_to "New Project", new_project_path %>

app/views/projects/new.html.erb
<h1>New Project</h1>

<%= render "form", project: @project %>

app/views/projects/show.html.erb
<h1><%= @project.title %></h1>

<p><%= @project.description %></p>

<ul>
  <li><%= link_to "Edit", edit_project_path(@project) %></li>
    <li><%= link_to "Destroy", project_path(@project), data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  } %></li>
  <li><%= link_to "Projects Index", root_path %></li>
</ul>

<hr />

<h2>Boards/Stages</h2>
<%= render @project.boards %>

<hr />

<h2>Add a Board:</h2>
<%= render 'boards/form'  %>

<hr />

app/views/tasks/_form.html.erb
<%= form_with model: [ @board, @board.tasks.build ] do |form| %>
  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </p>
  <p>
    <%= form.label :description %><br>
    <%= form.text_area :description %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/tasks/_form1.html.erb
<h2>Task Edit Form</h2>
<%= form_with model: task do |form| %>
  <div>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </div>
  <div>
    <%= form.label :description %><br>
    <%= form.text_area :description %>
  </div>
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/tasks/_task.html.erb
<p>
  <strong>Task :</strong>
  <%= link_to task.title, task %>
</p>

<p>
  <strong>Task Description:</strong>
  <%= task.description %>
</p>

app/views/tasks/edit.html.erb
<h1>Edit Task</h1>

<%= render "form1", task: @task %>

app/views/tasks/index.html.erb
<h1>Tasks</h1>
Board : <%= board.title %>
Project : <%= project.title %>

app/views/tasks/show.html.erb
<h1>Task Details</h1>
<!--
  To enable debugging in the view section
  <%# console %>
-->
<p>Title : <%= @task.title %></p>
<p>Description : <%= @task.description %></p>


<ul>
  <li><%= link_to "Edit", edit_task_path(@task) %></li>
    <li><%= link_to "Destroy", task_path(@task), data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  } %></li>
  <li><%= link_to "Projects Index", root_path %></li>
</ul>

<hr />

<h2>Board, Project Details</h2>
<p><strong>Board :</strong> <%= link_to @task.board.title, @board %></p>
<p><strong>Project :</strong> <%= link_to @task.board.project.title, @project %>

<hr />